# Generated by Django 2.0.13 on 2020-03-07 18:43

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)])),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_datetime', models.DateTimeField(default=datetime.datetime(2020, 3, 7, 18, 43, 18, 229752))),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(100)])),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Contact')),
            ],
        ),
    ]
