# Generated by Django 2.0.13 on 2020-03-07 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='contact_id',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='message',
            name='delivered_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 20, 55, 17, 863715)),
        ),
    ]
