# Generated by Django 2.0.13 on 2020-03-08 21:00

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200307_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='message',
            name='delivered_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 21, 0, 12, 893239)),
        ),
    ]
